CREATE TABLE transactions (
    id VARCHAR(50) PRIMARY KEY,
    bersama_booking_id VARCHAR(255) NOT NULL,
    sms_code VARCHAR(255),
    merchant_name VARCHAR(255) NOT NULL,
    keyword VARCHAR(255),
    otp INT,
    tcash_id VARCHAR(255),
    va_bca INT,
    mt_tid VARCHAR(255),
    disbursement_id VARCHAR(255),
    payment_method VARCHAR(255),
    status_code INT,
    item_name VARCHAR(255) NOT NULL,
    route TEXT,
    mdm_trx_id VARCHAR(255),
    user_id VARCHAR(255),
    timestamp_request_date TIMESTAMP,
    timestamp_submit_date TIMESTAMP,
    timestamp_callback_date TIMESTAMP,
    timestamp_callback_result VARCHAR(255),
    stan VARCHAR(255),
    amount INT,
    client_appkey VARCHAR(255),
    appid VARCHAR(255),
    appkey VARCHAR(255),
    testing BOOLEAN,
    token VARCHAR(255),
    currency VARCHAR(10),
    net_settlement FLOAT,
    price INT,
    bodysign TEXT,
    user_mdn VARCHAR(15),
    redirect_url TEXT,
    redirect_target TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
